### ISSUE TITLE
Deleting role assignment generating invalid GET request

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpcore#1208]
## Category

- [x] Bug

## Describe the bug

There looks to be a few issues with this one. From a quick look at the code, it looks to be a different cause to #1206.

When attempting to *delete* a role assignment, a ~~GET~~ request is sent to attempt to get the assignment by ID, this is pointing to the wrong URL, which #1207 should resolve. 

It also looks like the ID is not getting correctly substituted (and not caught at runtime like it is in #1206), causing a request to be sent without the ID, resulting in a 400 response:

```
The expression "Web/RoleAssignments/GetByPrincipal({PrincipalId})" is not valid.
```

## Steps to reproduce

1. Add one or more role assignments to a site for custom SP groups.
2. Run below code snippet
1. Experience error

```cs
var roleAssignments = await context.Web.RoleAssignments.ToListAsync();
foreach (var roleAssignment in roleAssignments)
{
    Console.WriteLine(roleAssignment.PrincipalId); // just for the sake of reading the principal id
    await roleAssignment.DeleteAsync();
}
```

## Expected behavior

A valid DELETE request is sent, or valid request to the `removeroleassignment` endpoint, and the role assignment is correctly removed.

## Environment details (*development & target environment*)

- **SDK version**: 1.9.72-nightly
- **OS**: Windows 11
- **SDK used in**: Azure Functions
- **Framework**: .NET 6
- **Tooling**: Jetbrains Rider

**Comment by jansenbe** [comment]
@JakeStanger : thanks for raising this and for the PR to fix the issue. I've just merged the PR, will be part of the next nightly, hence I'll close this issue now.

**Comment by JakeStanger** [comment]
@jansenbe thanks for merging the PR but the issue is still not fixed, as the ID is still not being substituted. 

The new nightly is resulting in a 400 with the following message:

```
The expression "Web/RoleAssignments/GetByPrincipalId({PrincipalId})" is not valid.
```

**Comment by jansenbe** [comment]
@JakeStanger : now it's fixed, I've added test cases to cover the RoleAssignment deletions when used on Web, List and ListItem.
