### ISSUE TITLE
[BUG] Get-PnPGroupPermissions: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by adzero** [pnp/pnpcore#408]
### Reporting an Issue
Get-PnPGroupPermissions raises "Object reference not set to an instance of an object" exception when using existing group title as Identity.

### Expected behavior 
Expecting to get permissions for a group identified by its title.

### Actual behavior 
Command raises a NullReferenceException when specifying a group name (existing or not). 
Notice that no exception occurs when passing a group object or its Id... and of course no results either. 

### Steps to reproduce behavior
```
Connect-PnPOnline -Url $url -Credentials $credentials
$group = Get-PnPGroup -AssociatedOwnerGroup
Get-PnPGroupPermissions -Identity $group.Title
```

### What is the version of the Cmdlet module you are running?
PnP.PowerShell version 1.3.19-nightly (same with 1.2.6-nightly)

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jansenbe** [comment]
I've just fixed an issue with special characters in site names: https://bertonline.sharepoint.com/sites/prov-1/bäüößcc now can be used as a site URL. Will check if there's additional work needed for the group permissions

**Comment by jansenbe** [comment]
@rom-1 / @adzero : I'm not able to repro the group name special character issue when the site url does **not** contain special chars. When the site name contains special there was an error, which will be fixed in the next nightly builds. Can you confirm the site url of the site's you see this issue on?

![image](https://user-images.githubusercontent.com/7451219/116521206-f3654c00-a8d3-11eb-978c-8a721a226de8.png)

**Comment by rom-1** [comment]
@jansenbe The site url from my specific example does not contain a special character, it is: `https://contoso.sharepoint.com/sites/workspace/Suess/`
This is also the url I am connecting to using Connect-PnPOnline. 

Screenshot using PnP.Powershell v1.5.0:
![2021-04-29_13h18_08](https://user-images.githubusercontent.com/37835829/116542997-9bd3da00-a8ed-11eb-9815-baae35ab69ac.png)

**Comment by jansenbe** [comment]
@rom-1 : would it be possible to start Fiddler, then start PS and provide me a trace of the Get-PnPGroup and Get-PnPGroupPermissions calls. Feel free to send to bjansen@microsoft.com. This will help diagnose, the issue I've fixed today seems to be different.

Also give `Get-PnPPage -Identity h` a try on your site, should not error out.

**Comment by rom-1** [comment]
sure thing, just give me some time please. I am stuck in meetings today/tomorrow, and don't have a fiddler ready to use. Thanks for taking a look into this! :-)

**Comment by rom-1** [comment]
`Get-PnPPage -Identity h` throws an error on that subsite, but I have no idea if this is normal behaviour for the parameter "h"
![2021-04-29_16h24_35](https://user-images.githubusercontent.com/37835829/116566878-663bea80-a907-11eb-8ce7-34ab3a86bbe1.png)

**Comment by jansenbe** [comment]
I asked the `get-pnppage` as that also uses PnP Core SDK under the covers...the fact that fails might indicate something in the site url as well. But let's wait for the Fiddler trace, in my lab I can uses sites/groups with special characters in them and things do work, so wondering why it's failing for you. Also please give it a try using the latest nightly build, version 1.5 has been out for a while now and the nightly builds contain a lot of fixes.

**Comment by rom-1** [comment]
I tried it again using v1.5.29-nightly, same issue. 
I sent the fiddler export a few minutes ago to your email address. This is an export for the 2 commands we have problems with (Get-PnPGroupPersmission, Get-PnPPage).

**Comment by jansenbe** [comment]
@rom-1 : there's a difference in how the API call is encoded, need to figure out why...see below for details

`Get-PnPGroupPermissions "group äüöß"` results in `GET <site>/_api/Web/SiteGroups?$filter=(Title+eq+%27group+%c3%a4%c3%bc%c3%b6%c3%9f%27+and+LoginName+eq+%27group+%c3%a4%c3%bc%c3%b6%c3%9f%27)&$top=1` which works.

In the your case I see `GET <site>/_api/Web/SiteGroups?%24filter=(Title+eq+%27SuedLink+Agentur+S%u00fcss+Besucher%27+and+LoginName+eq+%27SuedLink+Agentur+S%u00fcss+Besucher%27)&%24top=1` which fails.
```

**Comment by jansenbe** [comment]
So when using PS7 (.NET Core) this works...when using PS5 (.NET Framework) it fails....seems that there's a different encoding going on in .NET causing the problem. At least we're one step further now :-)

**Comment by jansenbe** [comment]
![image](https://user-images.githubusercontent.com/7451219/116684644-7c05ea00-a9b1-11eb-944f-1d2c094a8f26.png)
 versus
![image](https://user-images.githubusercontent.com/7451219/116684706-8cb66000-a9b1-11eb-8079-dc8287559fbd.png)

**Comment by jansenbe** [comment]
@rom-1 / @adzero  : I've just pushed a PnP Core SDK fix that handles the difference in encoding between .NET framework and .NET Core/.NET 5. Please try with tomorrow's nightly release and let me know how things go.

**Comment by rom-1** [comment]
@jansenbe Tried with v1.5.32-nightly, and the cmdlets "Set-pnpgrouppermissions" and "Get-pnpgrouppersmission" seem to work flawless now. `Get-PnPPage -Identity h` still throws the error "Object reference not set to an instance of an object.", but this might be normal as I don't know the expected output of this command.

![2021-05-03_11h29_53](https://user-images.githubusercontent.com/37835829/116861119-e497d580-ac02-11eb-8e7a-a9b13724ebed.png)

**Comment by jansenbe** [comment]
Issue has been resolved
